### ISSUE TITLE
epcc_currency allows more than one 'default' currency

### ISSUE THREAD

**Issue by dmacbride-ep** [elasticpath/terraform-provider-epcc#103]
The EPCC provider should prevent the user from configuring two _default_ currencies. It allows the user to define two default currencies in terraform, and the last one applied is the one that does become the default in EPCC. This results in a disconnect between the Terraform state and the EPCC state: terraform thinks both have the attribute `default` set to `true`, but EPCC says differently, so subsequent `terraform apply` effort keeps toggling the default value between the currencies.

Steps

1. Define two EPCC currencies for your store, Set `default=true` for both

```
resource "epcc_currency" "EUR" {
  code               = "EUR"
  exchange_rate      = 2
  format             = "{price}€"
  decimal_point      = "."
  thousand_separator = ","
  decimal_places     = 0
  default            = true
  enabled            = true
}

resource "epcc_currency" "CAD" {
  code               = "CAD"
  exchange_rate      = 2
  format             = "$${price}"
  decimal_point      = "."
  thousand_separator = ","
  decimal_places     = 0
  default            = true
  enabled            = true
}
```

1. Run `terraform apply`. Note that it is successful
1. Run `terraform apply` again. Note that it says it need to update one of the currencies to `~ default            = false -> true` 
1. Rerunning `terraform apply` always results in some change being required.

### Expected Results

Some validation would occur saying that the config described in the terraform files config is invalid

**Comment by razkevich** [comment]
I was looking at the documentation and it looks like that there's no way to validate terraform resources against other resources values or even presence. One example is the `aws_iam_policy_attachment` where the best they do is put a huge red warning in the documentation noting the side effects of not configuring this resource the way they expect. 

One thing we can do though is extract a separate resource called `epcc_default_currency` that would reference an existing `epcc_currency`. Maybe it'll make it less error prone? However there'll be no way to validate that there's only one `epcc_default_currency` in the `*.tf` files. Thoughts @steve-r-west , @dmacbride-ep ?

**Comment by dmacbride-ep** [comment]
I'm glad we investigated further - thanks so much @razkevich . Given the findings, I think it's fine to live with this limitation. Perhaps we document it well in a place that users will see it; perhaps that in the examples/resources/currency_resource/resource.tf example?
